# If you change this file, please restart the server process.
title: Inside Covve blog
description: Stories from Covve team’s journey towards building the ultimate address book.
twitter_username: covve
github_username: covve
baseurl: ""
url: "https://inside.covve.com"
permalink: /:title/


# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - .DS_Store
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-redirect-from

# Authors
ap:
    name: Alex Protogerellis
    link: http://uk.linkedin.com/in/protogerellis/
ma:
    name: Michael Asimakopoulos
    link: https://github.com/masimplo
zm:
    name: Zafeiris Malafouris
    link: https://twitter.com/zafeirism
vn:
    name: Valadis Novakovits
    link: https://twitter.com/el_nova
mk:
    name: Manolis Koufidakis
    link: http://gr.linkedin.com/in/mkoufidakis/
ka:
    name: Kostas Antonopoulos
    link: https://github.com/kostassite