# If you change this file, please restart the server process.
title: Inside Covve blog
description: Stories from Covve team’s journey towards building the ultimate address book.
twitter_username: covve
github_username: covve
baseurl: ""
url: "https://inside.covve.com"
permalink: /:title/


# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - .DS_Store
sass:
  sass_dir: _sass
  style: compressed


# Authors
ap:
    name: Alex Protogerellis
    link: https://github.com/alexproto
ma:
    name: Michael Asimakopoulos
    link: https://github.com/masimplo
zm:
    name: Zafeiris Malafouris
    link: https://github.com/zafeirism
vn:
    name: Valadis Novakovits
    link: https://github.com/vnovakovits
mk:
    name: Manolis Koufidakis
    link: https://github.com/ManolisKoufidakis
ka:
    name: Kostas Antonopoulos
    link: https://github.com/kostassite